### ISSUE TITLE
Missing Repositories

### ISSUE THREAD

**Issue by wbuchanan** [IQSS/open-source-at-harvard#12]
Just wanted to point out some additional repositories related to one of the projects at a HGSE based research center : [OpenSDP](https://github.com/OpenSDP).

**Comment by pdurbin** [comment]
@wbuchanan thanks! Are you interested in making a pull request? Here's the file to edit: https://github.com/IQSS/open-source-at-harvard/blob/master/github.tsv

**Comment by wbuchanan** [comment]
@pdurbin 
PR Submitted

**Comment by pdurbin** [comment]
@wbuchanan thanks! I just merged your pull request (#13).

I remember you from https://github.com/wbuchanan/data-transfer 😄
