### ISSUE TITLE
Include public LTS projects

### ISSUE THREAD

**Issue by daveneiman** [IQSS/open-source-at-harvard#16]
The most important project in the harvard-lts public GitHub is [FITS](https://github.com/harvard-lts/fits) (File Information Tool Set):
https://github.com/harvard-lts/fits
There are other projects in this repo but are either less important or inactive.
Might also want to consider [FITSServlet](https://github.com/harvard-lts/FITSservlet)
https://github.com/harvard-lts/FITSservlet

**Comment by pdurbin** [comment]
@daveneiman "fits" and "FITSservlet" were added in the first commit at 2f54f12 so it sounds like we're all set. Please keep the feedback coming! Thanks!
