### ISSUE TITLE
Could we submit more projects?

### ISSUE THREAD

**Issue by sudoghut** [IQSS/open-source-at-harvard#24]
Hi, I am the senior project manager of China Biographical Database project(CBDB project) in IQSS, Hongsu Wang. Could we add more projects to open-source-at-harvard? Thanks a lot!
https://github.com/cbdb-project/cbdb-online-main-server
https://github.com/cbdb-project/accessAndMySQLTransfer
https://github.com/cbdb-project/cbdb-online-query-app
https://github.com/cbdb-project/ip-director

**Comment by pdurbin** [comment]
@sudoghut absolutely. Please just make a pull request. Thanks.

**Comment by sudoghut** [comment]
Cool! Thanks a lot! When I tried to submit a pr, I found that I can't do this
![image](https://user-images.githubusercontent.com/8538710/85903591-40ead580-b839-11ea-989d-edbe04f5cd97.png)

Would you like to add me to IQSS organization? Thanks!

**Comment by pdurbin** [comment]
@sudoghut adding you to the IQSS organization shouldn't be necessary. Can you please try forking the repo and then creating a branch on your fork? And then create a pull request from that branch.

**Comment by sudoghut** [comment]
Thanks for your suggestion! A new pr has been submitted.
